apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "turnstile-appcheck-gateway.configMapName" . }}
  labels:
    {{- include "turnstile-appcheck-gateway.labels" . | nindent 4 }}
data:
  {{- range $key := keys .Values.config | sortAlpha }}
  {{ $key }}: {{ index $.Values.config $key | quote }}
  {{- end }}
